baseURL: https://www.cognitivespace.com/
languageCode: en-us
title: Cognitive Space
theme: nostyle
paginate: 12

frontmatter:
  lastmod:
  - lastmod
  - :fileModTime
  - :default

markup:
  goldmark:
    renderer:
      unsafe: true
